In [31]:
import numpy as np
a=np.array([
    [1, 2, 3],
    [7, 8 ,9],
    [4, 5, 6]
])
b=np.sort(a, axis=0)
c=b.T
d=np.vstack((a,c))
e=np.hstack((a,c))
f=np.concatenate((a, c), axis=None)

print('отсортированные столбцы: ', '\n', b)
print('транспонированный массив: ', '\n', c)
print('вертикальное объединение: ', '\n', d)
print('горизонтальное объединение: ', '\n', e)
print('объединение без оси: ', '\n', f)

отсортированные столбцы:  
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
транспонированный массив:  
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
вертикальное объединение:  
 [[1 2 3]
 [7 8 9]
 [4 5 6]
 [1 4 7]
 [2 5 8]
 [3 6 9]]
горизонтальное объединение:  
 [[1 2 3 1 4 7]
 [7 8 9 2 5 8]
 [4 5 6 3 6 9]]
объединение без оси:  
 [1 2 3 7 8 9 4 5 6 1 4 7 2 5 8 3 6 9]


In [133]:
import numpy as np
import math as m
def what_type(a):
    if np.amin(a) < 0:
        if abs(np.amax(a)) < abs(np.amin(a)):
            eltype=m.ceil(np.log(abs(np.amin(a)))/np.log(2))
        else:
            eltype=m.ceil(np.log(np.amax(a))/np.log(2))
        dtype=np.int8
    else:
        eltype=m.ceil(np.log(np.amax(a))/np.log(2))
        if eltype<11:
            dtype=np.uint8
        else:
            dtype=np.uint64
    return dtype

n=int(input())
a=[]
for i in range (n):      
    a.append(int(input()))
dtype=what_type(a)
row = np.array(a, dtype=dtype)
print(row)

4
12000000
123000
500000
11999999
[12000000   123000   500000 11999999]


In [15]:
import numpy as np

def reading (name):
    f=open(name, 'r')
    Flag=True
    x=[]
    name=[]
    c0=[]
    c1=[]
    c3=[]
    for line in f: 
        if Flag==True:
            a=line.split()
            name.append(a[0])
            name.append(a[1])
            name.append(a[2])
            name.append(a[3])
        if Flag==False:
            a=line.split()
            x.append((a[0], a[1], int(a[2]), a[3]))
            c0.append(len(a[0]))
            c1.append(len(a[1]))
            c3.append(len(a[3]))
        Flag=False
    c0=max(c0)
    c1=max(c1)
    c3=max(c3)
    x=np.array(x, dtype=[(name[0], str, c0), (name[1], str, c1), (name[2], int), (name[3], str, c3)])
    f.close()  
    return x, name

x, name = reading('cell_culture.txt')
print('структурированный список: ', '\n', x)

amount=sum(x[x[name[0]] == '5-Apr'][name[2]])
print('заказано на 5 апреля: ', amount)

people=x[x[name[0]] == '9-Apr'][name[1]]
print('кто заказывал на 9 апреля: ', people)

структурированный список:  
 [('5-Apr', 'Liza',   3, 'Transfection') ('5-Apr', 'Dasha',  40, 'Virus')
 ('5-Apr', 'Dima', 300, 'Biomass') ('9-Apr', 'Dasha', 300, 'Biomass')
 ('9-Apr', 'Liza',  40, 'Virus') ('8-Apr', 'Dasha',   1, 'Titer')]
заказано на 5 апреля:  343
кто заказывал на 9 апреля:  ['Dasha' 'Liza']
